using System.Globalization;
using System.Resources;

namespace DiscordBot.BusinessLogic
{
    public static class LocalizatorLegacy
    {
        private readonly static ResourceManager ResourceManager;

        static LocalizatorLegacy()
        {
            ResourceManager = new ResourceManager(typeof(Resources.CommandAction.Resources));
        }

        public static string Localize(string key,CultureInfo cultureInfo)
        {
            return GetString(key, cultureInfo);
        }

        public static string GetString(string key, CultureInfo culture) // God i love chat GPT. All below generated by him/her... they?
        {
            // Try to get the localized string for the specified key and culture.
            var resourceSet = ResourceManager.GetResourceSet(culture, true, true);
            var value = resourceSet?.GetString(key);

            // If the localized string is not found and the current culture is not
            // the default culture, try to get the localized string from the default
            // culture's resource file.
            if (value == null && culture != CultureInfo.InvariantCulture)
            {
                var defaultCulture = CultureInfo.GetCultureInfo("en-US");
                resourceSet = ResourceManager.GetResourceSet(defaultCulture, true, true);
                value = resourceSet?.GetString(key);
            }

            // If the localized string is still not found, return the key itself.
            return value ?? key;
        }
    }
}