//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordBot.BusinessLogic.Resources.CommandAction {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscordBot.BusinessLogic.Resources.CommandAction.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send message to chat GPT (3.5).
        /// </summary>
        internal static string AIChatDescription {
            get {
                return ResourceManager.GetString("AIChatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Await response....
        /// </summary>
        internal static string AIMessageSended {
            get {
                return ResourceManager.GetString("AIMessageSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied.
        /// </summary>
        internal static string Applied {
            get {
                return ResourceManager.GetString("Applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoffeeBracke command. Input time after command. Press to emoji below answer to be notified when the timer goes off..
        /// </summary>
        internal static string CBCommandDesc {
            get {
                return ResourceManager.GetString("CBCommandDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command example !cb 19:00.
        /// </summary>
        internal static string CBCommandExample {
            get {
                return ResourceManager.GetString("CBCommandExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Its coffee break time! {0}.
        /// </summary>
        internal static string CBCommandTimerIsDue {
            get {
                return ResourceManager.GetString("CBCommandTimerIsDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer will fire in {0} hours {1} minutes. Press emoji to get notified!.
        /// </summary>
        internal static string CBCommandTimerSetted {
            get {
                return ResourceManager.GetString("CBCommandTimerSetted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command entered without time..
        /// </summary>
        internal static string CBInputError {
            get {
                return ResourceManager.GetString("CBInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context lenght exceeded for current model.
        /// </summary>
        internal static string context_length_exceeded {
            get {
                return ResourceManager.GetString("context_length_exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot test. Respond with text after command or &quot;Hello&quot; if command empty.
        /// </summary>
        internal static string EchoCommandDesc {
            get {
                return ResourceManager.GetString("EchoCommandDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello there.
        /// </summary>
        internal static string EchoDefaultResponse {
            get {
                return ResourceManager.GetString("EchoDefaultResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error encountered. You can try again.
        /// </summary>
        internal static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant parse value.
        /// </summary>
        internal static string ParsingError {
            get {
                return ResourceManager.GetString("ParsingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get bot localization.
        /// </summary>
        internal static string SettingsGetCurrentLocale {
            get {
                return ResourceManager.GetString("SettingsGetCurrentLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get sever timezone.
        /// </summary>
        internal static string SettingsGetTimeZone {
            get {
                return ResourceManager.GetString("SettingsGetTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale setted.
        /// </summary>
        internal static string SettingsLocaleSettedtCurrentLocale {
            get {
                return ResourceManager.GetString("SettingsLocaleSettedtCurrentLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set bot localization.
        /// </summary>
        internal static string SettingsSetCurrentLocale {
            get {
                return ResourceManager.GetString("SettingsSetCurrentLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set timezone offset from utc.
        /// </summary>
        internal static string SettingsSetTimeZone {
            get {
                return ResourceManager.GetString("SettingsSetTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command example for UTC +5 !SetTZ 5 .
        /// </summary>
        internal static string SettingsSetTimeZoneExample {
            get {
                return ResourceManager.GetString("SettingsSetTimeZoneExample", resourceCulture);
            }
        }
    }
}
